{ pkgs, mods, }:

  with mods; [
    JIP-LN-NVSE
    JIP-LN-Config
    FalloutCustom
    JohnnyGuitarNVSE
    JohnnyGuitar-Tweaks-Config
    ShowOff-NVSE
    NVTF
    NVTF-Config
    kNVSE
    kNVSE-Config
    UIO
    UIO-Config
    ModLimitFix
    CrashLogger
    ImprovedConsole
    ImprovedConsole-Config
    ConsolePaste
    ShaderLoaderNVSE
    ISControl
    NoExitToMainMenu
    FogBasedObjectCulling
    zLibUpdated
    YUP
    YUPDate
    Unoffical-Patch-NVSE-Plus
    IStewieAIs-Tweaks-and-Engine-Fixes
    IStewieAIs-Tweaks-and-Engine-Fixes-VNV-Config
    IStewieAIs-Engine-Optimizations
    Combat-Lag-Fix
    VATS-Lag-Fix
    ActorCause-Save-Bloat-Fix
    Viewmodel-Shake-Fix
    NVMIM
    NVMIM-YUP-Patch
    PipBoyOn-Node-Fixes
    MAC-10
    ITEM
    Climate-Control
    Misc-Audio-Tweaks-and-Fixes
    MoonlightNVSE
    MoonlightNVSE-Config
    Fallout-Alpha-Rendering-Tweaks
    Fallout-Alpha-Rendering-Tweaks-Config
    Exterior-Emittance-Fix
    LOD-Fixes-and-Improvements
    LOD-Fixes-and-Improvements-Config
    LOD-Flicker-Fix
    Improved-Lighting-Shaders
    Improved-Lighting-Shaders-Config
    mods."3rd-Person-Animations-Fixpack"
    Muzzle-Flash-Light-Fix
    Viewmodel-Shading-Fix
    Blood-Decal-Flashing-Fix
    Depth-of-Field-Fix
    Landscape-Disposition-Fix
    Vanilla-Placement-Fixes
  ] 
