{ pkgs, ... }: rec {

  workers-and-resources-base = pkgs.stdenvNoCC.mkDerivation {
    name = "workers-and-resources-base";
    exeSrc = pkgs.requireFile {
      name = "setup_workers__resources_soviet_republic_1.1.1.6.1_88339.exe";
      url = "https://www.gog.com/en/game/workers_resources_soviet_republic";
      sha256 = "1amrz7yhvn7h2xflaj4xp9bj59vnxcjviq02v4qylmaaf1zzpgk3";
    };
    binSrc = pkgs.requireFile {
      name = "setup_workers__resources_soviet_republic_1.1.1.6.1_88339-1.bin";
      url = "https://www.gog.com/en/game/workers_resources_soviet_republic";
      sha256 = "1z4z13ywcf3n913zi80fqm80hdlgds3j70izwf7wsx7wjn6lsgaq";
    };
    dontUnpack = true;
    nativeBuildInputs = [ pkgs.innoextract pkgs.python3 ];
    installPhase = ''
      mkdir $out
      cp $exeSrc $(stripHash $exeSrc)
      cp $binSrc $(stripHash $binSrc)
      innoextract $(stripHash $exeSrc)
      rm $(stripHash $exeSrc) $(stripHash $binSrc)
      cp -r * $out/
      rm $out/env-vars
    '';
  };
  config-ini = pkgs.writeTextDir "media_soviet/config.ini" ''
$INT DIRECTX11 1
$INT MONITOR 0
$INT RESOLUTIONX 1289
$INT RESOLUTIONY 859
$INT WINDOWED 0
$INT VOLUME_SOUND 80
$INT VOLUME_SOUND_UI 80
$INT VOLUME_MUSIC 80
$INT AUTOSAVE 0
$INT AUTOSAVE_NUM 0
$INT AUTOSAVE_INTERVAL 1
$INT GUI_SIZE -1
$INT GRAPHIC_DRAWDISTANCE 3000
$INT GRAPHIC_TERRAINDETAIL 0
$INT GRAPHIC_SHADOWDETAIL 0
$INT GRAPHIC_TREEDETAIL 0
$INT GRAPHIC_DOFDETAIL 0
$INT GRAPHIC_GRASS 0
$INT GRAPHIC_CITIZENS 2
$INT GRAPHIC_VSYNC 0
$INT GRAPHIC_AA -1
$INT GRAPHIC_SMOOTHPARTICLES 0
$INT GRAPHIC_LESSPARTICLES 0
$INT GRAPHIC_CLOUDSDETAIL 0
$INT GRAPHIC_SSAO 0
$INT GRAPHIC_WATER 0
$INT OPTIMIZATION_SAVE_VRAM_TEXTURES 0
$INT WORKSHOP_OVERRIDE 0
$INT WINDOW_PAUSE 0
$INT WINDOW_MINIMIZE 0
$INT FASTINIT_BUILDINGS 1
$INT FASTINIT_VEHICLES 1
$TEXT LANGUAGE2 auto
$TEXT WORLDCONFIG terrain3
$INT AFTERSOUNDUPDATE 1
$INT DISABLEWORKSHOP 0
$INT DISABLESUBSCRIBED 0
$INT WORKSHOPADVANCEDLOG 0
$TEXT HOTKEY_00 null
$TEXT HOTKEY_01 null
$TEXT HOTKEY_02 null
$TEXT HOTKEY_03 null
$TEXT HOTKEY_04 null
$TEXT HOTKEY_05 null
$TEXT HOTKEY_06 null
$TEXT HOTKEY_07 null
$TEXT HOTKEY_08 null
$TEXT HOTKEY_09 null
$TEXT HOTKEY_10 null
$TEXT HOTKEY_11 null
$TEXT HOTKEY_12 null
$TEXT HOTKEY_13 null
$TEXT HOTKEY_14 null
$TEXT HOTKEY_15 null
$TEXT HOTKEY_16 null
$TEXT HOTKEY_17 null
$TEXT HOTKEY_18 null
$TEXT HOTKEY_19 null
$TEXT HOTKEY_20 null
$TEXT HOTKEY_21 null
$TEXT HOTKEY_22 null
$TEXT HOTKEY_23 null
$TEXT HOTKEY_24 null
$TEXT HOTKEY_25 null
$TEXT HOTKEY_26 null
$TEXT HOTKEY_27 null
$TEXT HOTKEY_28 null
$TEXT HOTKEY_29 null
$TEXT HOTKEY_30 null
$TEXT HOTKEY_31 null
$TEXT HOTKEY_32 null
$TEXT HOTKEY_33 null
$TEXT HOTKEY_34 null
$TEXT HOTKEY_35 null
$TEXT HOTKEY_36 null
$TEXT HOTKEY_37 null
$TEXT HOTKEY_38 null
$TEXT HOTKEY_39 null
$TEXT HOTKEY_40 null
$TEXT HOTKEY_41 null
$TEXT HOTKEY_42 null
$TEXT HOTKEY_43 null
$TEXT HOTKEY_44 null
$TEXT HOTKEY_45 null
$TEXT HOTKEY_46 null
$TEXT HOTKEY_47 null
$TEXT HOTKEY_48 null
$TEXT HOTKEY_49 null
$TEXT HOTKEY_50 null
$TEXT HOTKEY_51 null
$TEXT HOTKEY_52 null
$TEXT HOTKEY_53 null
$TEXT HOTKEY_54 null
$TEXT HOTKEY_55 null
$TEXT HOTKEY_56 null
$TEXT HOTKEY_57 null
$TEXT HOTKEY_58 null
$TEXT HOTKEY_59 null
$TEXT HOTKEY_60 null
$TEXT HOTKEY_61 null
$TEXT HOTKEY_62 null
$TEXT HOTKEY_63 null
$TEXT HOTKEY_64 null
$TEXT HOTKEY_65 null
$TEXT HOTKEY_66 null
$TEXT HOTKEY_67 null
$TEXT HOTKEY_68 null
$TEXT HOTKEY_69 null
$TEXT HOTKEY_70 null
$TEXT HOTKEY_71 null
$TEXT HOTKEY_72 null
$TEXT HOTKEY_73 null
$TEXT HOTKEY_74 null
$TEXT HOTKEY_75 null
$TEXT HOTKEY_76 null
$TEXT HOTKEY_77 null
$TEXT HOTKEY_78 null
$TEXT HOTKEY_79 null
$TEXT HOTKEY_80 null
$TEXT HOTKEY_81 null
$TEXT HOTKEY_82 null
$TEXT HOTKEY_83 null
$TEXT HOTKEY_84 null
$TEXT HOTKEY_85 null
$TEXT HOTKEY_86 null
$TEXT HOTKEY_87 null
$TEXT HOTKEY_88 null
$TEXT HOTKEY_89 null
$TEXT HOTKEY_90 null
$TEXT HOTKEY_91 null
$TEXT HOTKEY_92 null
$TEXT HOTKEY_93 null
$TEXT HOTKEY_94 null
$TEXT HOTKEY_95 null
$TEXT HOTKEY_96 null
$TEXT HOTKEY_97 null
$TEXT HOTKEY_98 null
$TEXT HOTKEY_99 null
$INT FIXEDHINT_0 0
$INT FIXEDHINT_1 0
$INT FIXEDHINT_2 0
$INT FIXEDHINT_3 0
$INT FIXEDHINT_4 0
$INT FIXEDHINT_5 0
$INT FIXEDHINT_6 0
$INT FIXEDHINT_7 0
$INT FIXEDHINT_8 0
$INT FIXEDHINT_9 0
$INT FIXEDHINT_10 0
$INT FIXEDHINT_11 0
$INT FIXEDHINT_12 0
$INT FIXEDHINT_13 0
$INT FIXEDHINT_14 0
$INT FIXEDHINT_15 0
$INT FIXEDHINT_16 0
$INT FIXEDHINT_17 0
$INT SCREENSHOT_TIMELAPSE 0
$INT SCREENSHOT_FREQUENCY 100
$INT SCREENSHOT_ORDER 0
$TEXT_SPACE SCREENSHOT_PREFIX "screenshot"
$FLOAT SCREENSHOT_CAMX 0.00
$FLOAT SCREENSHOT_CAMY 0.00
$FLOAT SCREENSHOT_CAMZ 0.00
$FLOAT SCREENSHOT_CAM_VX 0.00
$FLOAT SCREENSHOT_CAM_VY 0.00
$FLOAT SCREENSHOT_CAM_VZ 1.00
$INT WARNING_MESSAGE_CITIZEN_HAPINESS 1
$INT WARNING_MESSAGE_CITIZEN_HEALTH 1
$INT WARNING_MESSAGE_CITIZEN_UNEMPLOYED 1
$INT WARNING_MESSAGE_CITIZEN_AMBULANCE 1
$INT WARNING_MESSAGE_CITIZEN_LOYALTY 1
$INT WARNING_MESSAGE_BUILDING_HEATING 1
$INT WARNING_MESSAGE_BUILDING_ELECTRIC 1
$INT WARNING_MESSAGE_TRAFFIC_JAM 1
$INT WARNING_MESSAGE_TRAIN_COLLISION 1
$INT WARNING_MESSAGE_TRAIN_SIGNAL 1
$INT WARNING_MESSAGE_SHOP_GODS 1
$INT WARNING_MESSAGE_FACTORY_PRODUCTION 1
$INT WARNING_MESSAGE_CITIZEN_POLICY 1
$INT WARNING_MESSAGE_CITIZEN_CRIME 1
$INT WARNING_MESSAGE_ORPHANAGE 1
$INT WARNING_MESSAGE_GARBAGE_FULL 1
$INT WARNING_MESSAGE_FIRES 1
$INT MESSAGE_POPUP_RED 1
$INT MESSAGE_POPUP_YELLOW 1
$INT MESSAGE_POPUP_GREEN 1
$INT MESSAGE_POPUP_BLUE 1
$INT TRAINS_ON_LEFT_SIDE 1
$INT BOTTOMMENU_WORKSHOP 1
$INT BOTTOMMENU_EDITOR 1
$INT WINDOW_AUTOCLOSING 1
$INT WINDOW_OPEN_ON_LEFT 0
$INT AUTOHIDE_LEFT_BAR 0
$INT AUTOHIDE_BOTTOM_MENU 0
$INT BOTTOM_MENU_LEVEL_1_SCALE 0
$INT BOTTOM_MENU_LEVEL_2_SCALE 100
$INT BOTTOM_MENU_ON_TOP 0
$INT SHOW_CONTROL_HINTS 1
$INT WORKSHOP_ENUMERATE_USED_ONLY 0
$INT UNITS_METRIC_IMPERIAL 0
$INT AUTOSAVE_TO_ZIP 0
$INT USE_MENU_ZOOM 0
$FLOAT CONTROLLER_BIAS 0.30
$INT TUTORIAL_COMPLETED_1 0
$INT TUTORIAL_COMPLETED_2 0
$INT TUTORIAL_COMPLETED_3 0
$INT TUTORIAL_COMPLETED_4 0
$INT TUTORIAL_COMPLETED_5 0
$INT TUTORIAL_COMPLETED_6 0
$INT TUTORIAL_COMPLETED_7 0
$INT TUTORIAL_COMPLETED_8 0
$INT TUTORIAL_COMPLETED_9 0
$INT TUTORIAL_COMPLETED_10 0
$INT TUTORIAL_COMPLETED_11 0
$INT TUTORIAL_COMPLETED_12 0
$INT TUTORIAL_COMPLETED_13 0
$INT TUTORIAL_COMPLETED_14 0
$INT TUTORIAL_COMPLETED_15 0
$INT TUTORIAL_COMPLETED_16 0
$INT TUTORIAL_COMPLETED_17 0
$INT TUTORIAL_COMPLETED_18 0
$INT CAMPAIGN_COMPLETED_1 1
$INT CAMPAIGN_COMPLETED_2 0
$INT CAMPAIGN_COMPLETED_3 0

$ENDs    
  '';

  workers-and-resources-unwrapped = pkgs.symlinkJoin {
    name = "workers-and-resources-unwrapped";
    paths = [
      workers-and-resources-base
      config-ini
    ];
  };
  workers-and-resources = pkgs.writeScriptBin "workers-and-resources" ''
    #!/usr/bin/env bash

    export WINEPREFIX=$HOME/.local/share/workers-and-resources/wine
    if [ ! -d $HOME/.local/share/workers-and-resources/game ]
    then
      mkdir -p $HOME/.local/share/workers-and-resources/game
    fi
    if [ ! -d ~/.local/share/workers-and-resources/save ]
    then
      mkdir -p ~/.local/share/workers-and-resources/save
    fi
    if [ ! "$(readlink $HOME/.local/share/workers-and-resources/game/SOVIET_g.exe)" = "${workers-and-resources-unwrapped}/SOVIET_g.exe" ]
    then
      rm -rf $HOME/.local/share/workers-and-resources/game/*
      cp -rs ${workers-and-resources-unwrapped}/* $HOME/.local/share/workers-and-resources/game/
      chmod +w $HOME/.local/share/workers-and-resources/game/ -R
      rm ~/.local/share/workers-and-resources/game/SOVIET64_g.exe
      cp -f ${workers-and-resources-unwrapped}/SOVIET64_g.exe ~/.local/share/workers-and-resources/game/SOVIET64_g.exe
      ln -s ~/.local/share/workers-and-resources/save ~/.local/share/workers-and-resources/game/media_soviet/save
    fi
    cd ~/.local/share/workers-and-resources/game/
    ${pkgs.umu-launcher}/bin/umu-run ~/.local/share/workers-and-resources/game/SOVIET64_g.exe
  '';

}
